services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - demo_network
  pgadmin:
    image: dpage/pgadmin4:7.7
    restart: always
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@dummy.xyz
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - demo_network
    depends_on:
      - postgres
  devcontainer:
    build:
      dockerfile: ./Dockerfile
      context: ./
    networks:
      - demo_network
    command: sleep infinity
networks:
  demo_network: